import numpy as np
import matplotlib.pyplot as plt


#Trying to understand how use the Borst_Fig1.py code to generate the figures in the paper. 

## First, I will try to understand the code and then I will try to generate the figures.
## This figure plots 3 graphs : a 2-D spatial receptive field, a 1-D spatial receptive field, and a temporal step response 
## For the receptive fields, 4 parameters are given : FWHM_center, FWHM_surrnd, surrnd_fac, and polarity
# The 1-D receptive field is generated by taking the center of the 2-D receptive field and plotting it. You take the center which should be 0 and then you plot that the graph would be x position over value of receptive field
# The temporal step response is generated by taking the stimulus, which is just a step function from 0-100, with the stimulus starting at 20 ms; then you put the stimulus into the lowpass filter and then the result of that into a high pass filter to plot what the actual repsonse of the neuron is 


# CONSTANTS 

STIM = np.zeros(100) #100 ms stimulation each index is 1 ms
STIM[20:99] = 1.0 #at 20 ms the stimulus is turned on and stays on until the end

LAMINA_NEURON = ['L1', 'L2', 'L3', 'L4', 'L5']
LAMINA_NEURON_FWHM_CENTER = [6.31,6.74,5.90,8.55,6.79] #filled  
LAMINA_NEURON_FWHM_SURROUND = [41.1,29.3,15.1,32.7,31.4] #filled
LAMINA_NEURON_SURROUND_FAC = [0.012,0.013,0.19,0.046,0.035] #filled
LAMINA_NEURON_POLARITY = [-1,-1,-1,-1,1] #filled 
LAMINA_NEURON_LP_TAU = [03.8,05.8,05.4,02.3,04.2] 
LAMINA_NEURON_HP_TAU = [39.1,28.8,00.0,38.1,12.7]

MEDULLA_NEURON_T4 = ['Mi1', 'Tm3', 'Mi4', 'Mi9']
MEDULLA_NEURON_T4_FWHM_CENTER = [6,12,6,6] 
MEDULLA_NEURON_T4_FWHM_SURROUND = [29,7,16,24]
MEDULLA_NEURON_T4_SURROUND_FAC = [0.022,0.000,0.132,0.063]
MEDULLA_NEURON_T4_POLARITY = [1,1,1,-1]
MEDULLA_NEURON_T4_LP_TAU = [05.4,02.7,03.8,07.7]
MEDULLA_NEURON_T4_HP_TAU = [31.8,26.0,0.00,0.00]

MEDULLA_NEURON_T5 = ['Tm1','Tm2','Tm4','Tm9']
MEDULLA_NEURON_T5_FWHM_CENTER = [6,12,6,6] 
MEDULLA_NEURON_T5_FWHM_SURROUND = [27,31,35,24]
MEDULLA_NEURON_T5_SURROUND_FAC = [0.040,0.035,0.054,0.046]
MEDULLA_NEURON_T5_POLARITY = [-1,-1,-1,-1]
MEDULLA_NEURON_T5_LP_TAU = [04.4,01.4,02.4,10.7]
MEDULLA_NEURON_T5_HP_TAU = [29.6,15.3,24.9,0.00]

RF_SIZE = 200 

#Receptive field 2-D field calculations functions 

#A general function that needs to create a gaussian function given a FWHM; this would be creating a field of nxn size with a width that is proportional to FWHM 

def gaussian_field(FWHM, size = RF_SIZE): 

    half_of_gaussian = size / 2 # 200 / 2 = 100

    #create grid 
    x = np.arange(-half_of_gaussian, half_of_gaussian, 1) #-100, 100, step size 1 
    y = np.arange(-half_of_gaussian, half_of_gaussian, 1)
    x , y = np.meshgrid(x,y) #meshgrid creates a coordinate system to refer to value of each coordinate. for instance x[0] will return the entire first row (-100, 99); x[0][0] will return -100
    #y[0][0] will return -100; the coordinate system is flipped, but in the end it doens't matter as r squares both y and x 

    r = np.sqrt(x**2 + y**2)

    #create gaussian distribution relative to specific FWHM
    sigma = FWHM / (2 * np.sqrt(2 * np.log(2))) 
    distribution = np.exp(-(r**2 / (2*sigma**2)))

    distribution = distribution / np.sum(distribution) #normalizes... makes sure area under curve is equal to 1 


    return distribution

# A function that genrates a 2-D receptive field 

def calc_rf(FWHM_center, FWHM_surrnd, surrnd_fac, polarity): 

    gaussian_center = gaussian_field(FWHM_center)
    gaussian_center = gaussian_center / np.max(gaussian_center)
    gaussian_surround = gaussian_field(FWHM_surrnd)
    gaussian_surround = gaussian_surround / np.max(gaussian_surround)
    rf = polarity * ( gaussian_center - (gaussian_surround * surrnd_fac) ) 
    rf = rf[80:121, 80:121] #borst crops to 40 x 40 to zoom into field. Cropped to 41 x 41 as need for rf response generation 

    return rf 


# Step function calculation 

#A function that defines what low pass given the stimulus function and lp_tau 

def low_pass(lp_tau, stim = STIM) : 

    size = len(stim) 
    response = np.zeros(size) 

    response[0] = stim[0]

    #create for loop that figures out each increment in response 
    if lp_tau < 1 :
        return stim 
    else :
        for i in range(size - 1) : 
            response[i+1] = 1 / lp_tau * (stim[i] - response[i]) + response[i] #step response 

    return response 


# A function that defines what high pass is 

def high_pass(hp_tau, response): 

    filtered = response - low_pass(hp_tau, response) 

    return filtered 

# copy pasted from Borst 

def normalize(x):
    
    mymax=np.nanmax(x)
    mymin=np.nanmin(x)
    
    if np.abs(mymax)>np.abs(mymin):
        absmax=np.abs(mymax)
    else:
        absmax=np.abs(mymin)
        
    result=x/absmax
    
    if mymax==mymin:
        result=x*0.0
        
    return result

# A fucntion that calculates the step response 

def calc_sr(lp_tau, hp_tau, polarity):

    low = low_pass(lp_tau)

    if hp_tau == 0:
        final_filtered = low
    else: 
        final_filtered = high_pass(hp_tau, low)

    final_filtered = normalize(final_filtered)   # from borst 

    #flip response if off neuron (polarity is -1)
    step_response =polarity*(final_filtered-0.5)+0.5 #from borst 

    return step_response 

# function that plots each figure 

def plot_neuron(axes, neuron_name, FWHM_center, FWHM_surround,surround_fac, polarity, lp_tau, hp_tau) :
    
    size = len(neuron_name)

    for i in range(size):

        #plot 1 : 2-D Receptive Field 
        rf = calc_rf(FWHM_center[i], 
                    FWHM_surround[i], 
                    surround_fac[i], 
                    polarity[i])
        
        axes[0,i].imshow(rf, cmap='PiYG', vmin=-1, vmax=1)
        axes[0,i].set_title(neuron_name[i])
        axes[0, i].set_xticks([0, 20, 40])
        axes[0,i].set_xticklabels([-20, 0, 20])
        axes[0, i].set_yticks([0, 20, 40])
        axes[0,i].set_yticklabels([-20, 0, 20])

        #plot 2 1-D Receptive Field 
        middle_plot = rf[20,:]
        if np.min(middle_plot)<-0.5: middle_plot = middle_plot + 1.0 #from borst 
        axes[1,i].plot(middle_plot)
        axes[1, i].set_xticks([0, 20, 40])
        axes[1,i].set_xticklabels([-20, 0, 20])
        axes[1, i].set_ylim(-0.2, 1.2) #for similarity 

        #plot 3 Step Response 
        low = calc_sr(lp_tau[i], hp_tau[i], polarity[i]) 
        axes[2,i].plot(low)
        axes[2, i].set_ylim(-0.2, 1.2) #for similarity  

    return 1

# Function that plots entire figure 

def plot_final_figure(title, output_dir):

    fig = plt.figure(figsize=(40, 40))
    subfigs = fig.subfigures(2, 2)
    
    axes_lamina = subfigs[0][0].subplots(3, 5)
    axes_t4 = subfigs[0][1].subplots(3, 4)
    axes_t5 = subfigs[1][0].subplots(3, 4)
    
    plot_neuron(axes_lamina, LAMINA_NEURON, LAMINA_NEURON_FWHM_CENTER, LAMINA_NEURON_FWHM_SURROUND, LAMINA_NEURON_SURROUND_FAC, LAMINA_NEURON_POLARITY, LAMINA_NEURON_LP_TAU, LAMINA_NEURON_HP_TAU)
    plot_neuron(axes_t4, MEDULLA_NEURON_T4, MEDULLA_NEURON_T4_FWHM_CENTER, MEDULLA_NEURON_T4_FWHM_SURROUND, MEDULLA_NEURON_T4_SURROUND_FAC, MEDULLA_NEURON_T4_POLARITY, MEDULLA_NEURON_T4_LP_TAU, MEDULLA_NEURON_T4_HP_TAU)
    plot_neuron(axes_t5, MEDULLA_NEURON_T5, MEDULLA_NEURON_T5_FWHM_CENTER, MEDULLA_NEURON_T5_FWHM_SURROUND, MEDULLA_NEURON_T5_SURROUND_FAC, MEDULLA_NEURON_T5_POLARITY, MEDULLA_NEURON_T5_LP_TAU, MEDULLA_NEURON_T5_HP_TAU)
    
    subfigs[1][1].text(0.5, 0.5, f"{title}", 
                   ha='center', va='center', 
                   fontsize=40)
    
    plt.savefig(output_dir, dpi=300, bbox_inches='tight') #in order to make sure figure saves properly dpi is resolution bbox is to make sure figure it not stretched / cropped 
    plt.show()


#final function 

output_dir = 'Aditi_fly_optic_lobe/Results/figure1.png'
title = "Figure one recreation"
#plot_final_figure(title, output_dir)

